/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jk;
import javax.swing.JOptionPane;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
/**
 *
 * @author Nigel Itotia
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logintext = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Passwordf = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        Loginbttn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);

        logintext.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        logintext.setPreferredSize(new java.awt.Dimension(156, 26));
        jPanel1.add(logintext);
        logintext.setBounds(475, 490, 410, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("Police Login");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(560, 390, 250, 40);

        Passwordf.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(Passwordf);
        Passwordf.setBounds(470, 580, 420, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nigel Itotia\\Pictures\\java\\zx.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1370, 780);

        Loginbttn.setText("jButton1");
        Loginbttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginbttnActionPerformed(evt);
            }
        });
        jPanel1.add(Loginbttn);
        Loginbttn.setBounds(1000, 670, 330, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1366, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginbttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginbttnActionPerformed
        // TODO add your handling code here:
        String password = Passwordf.getText();
        String username = logintext.getText();
        if (password.contains("Mshamba2#")&&(username.contains("000000")))
        {
            logintext.setText(null);
            Passwordf.setText(null);
            systemExit();
        }
        
        else
        {
            JOptionPane.showMessageDialog(null,"Wrong username or password","Login Error",JOptionPane.ERROR_MESSAGE);
            Passwordf.setText(null);
            logintext.setText(null);
        }
    }//GEN-LAST:event_LoginbttnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Loginbttn;
    private javax.swing.JPasswordField Passwordf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField logintext;
    // End of variables declaration//GEN-END:variables
private void systemExit()
    {
        WindowEvent winClosing = new WindowEvent (this, WindowEvent.WINDOW_CLOSING);
    }
}
